#!/bin/busybox sh

cat <<EOF
  _    _           _ _        _    _ _   _ _______
 | |/ (_)         | | |      | || | | \ | |__   __|
 | ' / _ _ __   __| | | ___  | || |_|  \| |  | |   
 |  < | | '_ \ / _` | |/ _ \ |__   _| . ` |  | |   
 | . \| | | | | (_| | |  __/    | | | |\  |  | |   
 |_|\_\_|_| |_|\__,_|_|\___|    |_| |_| \_|  |_|   

 Welcome to Kindle 4th Gen's Initial RAM Filesystem!

EOF

mount -t proc none /proc
mount -t sysfs none /sys

exec /bin/sh || echo
