#!/bin/sh

echo "Press [Enter] to go to Initramfs Prompt..."

read -t 3 -n 1 answer

if [ $? == 0 ]; then
  echo "Welcome to Kindle 4th Generation Initramfs Prompt!"

  mount -t devtmpfs none /dev
  mount -t proc none /proc
  mount -t sysfs none /sys

  exec /bin/sh
else
  exit
fi